### ISSUE TITLE
Should we add a TODO list so we don't overlap/override what we are working on?

### ISSUE THREAD

**Issue by Voxelity** [GTANetworkDev/Bridge-API-Documentation#5]
We can either add it to the Readme or create another markdown file.

For Example:
- [ ] ACL Methods 
- [ ]  Blip Methods
- [ ] Ped Methods
- [ ] Blip Properties
- [ ] Vehicle Properties

Obviously more organized and better formatting. I think it would be a good idea because it would prevent two or more people working on one thing at a time.  Feel free to +1 if you agree!

**Comment by GTANAdam** [comment]
Sure, lead the way with it

**Comment by xabier1989** [comment]
Would be great to be more organized, yes!

**Comment by Voxelity** [comment]
Pull request submitted, feel free to close this when it's merged. Thank you!
